# aplicacao_web_atendimento/constants.py

# --- CONTROLO DE FUNCIONALIDADES (FEATURE FLAGS) ---
# Altere para True para ativar a restrição de data mínima (ex: 3 dias atrás).
# Altere para False para desativar a restrição.
DATE_FILTER_ENABLED = False

# Opções para os menus
TAREFAS_OPCOES = [
    "ACODE - 2024", "ACODE - 2025", "ACODE - 2026", "ADMINISTRATIVO", 
    "CAMPANHA PBM", "CAMPANHAS", "COMERCIAL", "CONVENIO", "DEVOLUÇÕES", 
    "DÚVIDAS GERAIS", "FACHADA E LAYOUT", "FINANCEIRO", "LOGISTICA", 
    "MATERIAIS DE MARKETING", "MATERIAIS OBRIGATÓRIOS", "PBM", "PEDIDOS", 
    "SOMAR", "SUPORTE OPERACIONAL"
]

INDEX_RESPONSAVEIS_OPCOES = [
    "LÍVIA VICTORIA LOURENÇO", "NATÁLIA BICHOFF", "DIEGO CORRENTE TANACA", 
    "FABIO HENRIQUE DE PÁDUA", "MIGUEL KENJI IWAMOTO", "LUIZ FELIPHE MARROCO"
]

RESPONSAVEIS_OPCOES = INDEX_RESPONSAVEIS_OPCOES + ["VALERIA APARECIDA BONFIM SOARES"]

TIPOS_OPCOES = ["WHATSAPP", "TELEFONE", "EMAIL"]
ACOES_OPCOES = ["ATIVA", "PASSIVA"] 
CONVENIO_TAREFAS_OPCOES = ["SOLICITAÇÃO", "LIBERAÇÃO", "DÚVIDAS"]

# Mapeamento de responsável para função
FUNCAO_MAP = {
    "LÍVIA VICTORIA LOURENÇO": "FOCAL",
    "NATÁLIA BICHOFF": "FOCAL",
    "DIEGO CORRENTE TANACA": "COORDENADOR",
    "FABIO HENRIQUE DE PÁDUA": "AUDITOR",
    "MIGUEL KENJI IWAMOTO": "AUDITOR",
    "LUIZ FELIPHE MARROCO": "AUDITOR",
    "VALERIA APARECIDA BONFIM SOARES": "CONVENIO"
}